### PR TITLE
Added an active initiative and proposed project

### PR DESCRIPTION
**Pull request by jiteshpabla**

### CODE REVIEW

**Comment by ryzokuken** [comment]
Perhaps use Medium instead? Or `osdc.github.io/blog` on the new website?

**Comment by jiteshpabla** [comment]
I'd like to use medium, but you know how cyberoam works. We can definitely add a blog page to our new website, but making it as a separate project can reduce the entry barrier for new comers (I think).

**Comment by ryzokuken** [comment]
@jiteshpabla it could be definitely be treated as a separate project, all I meant was that it would still work as a sub-page to our original website (`osdc.surge.sh/blog`, for example). Also, people who wish to make blog posts can just write markdown files and Gatsby could render them as separate posts.

**Comment by jiteshpabla** [comment]
Yea, sounds good. We're on the same page. :p

**Comment by ryzokuken** [comment]
Great! Remove the repo link from the README and I'd love to merge this RN.

**Comment by ryzokuken** [comment]
Merged! 🎉

**Pull request merged**
