### PR TITLE
Change Meetups to Workshops

### PR DESCRIPTION
**Pull request by V1shvesh**

### CODE REVIEW

**Comment by ryzokuken** [comment]
@V1shvesh are you doing this on top of the current `master`? I don't think so.

Could you `fetch` the current `master` and `rebase` it on top of it?

**Comment by ryzokuken** [comment]
@V1shvesh I think this isn't relevant anymore? If so, please close it.

**Comment by darkHarry** [comment]
@V1shvesh close it.

**Comment by ryzokuken** [comment]
@darkHarry He didn't respond yet, closing.

**Pull request closed without merging**
